image: python:2.7

stages:
  - build
  - test

build_job:
  stage: build
  script:
    - virtualenv venv --python python2
    - source venv/bin/activate && python setup.py develop
  artifacts:
    paths:
      - venv

test_job:
  stage: test
  script:
    - source venv/bin/activate && py.test
